name: emoji_letters
description: A simple command-line application to convert regular text to emoji text to paste into the Slack.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies:
  args: ^2.3.1
